### PR TITLE
Add support for Python 3

### PR DESCRIPTION
**Pull request by federicobond**
All tests are green in supported Python versions.

### CODE REVIEW

**Comment by slezica** [comment]
Fantastic work! Very thorough.

To spot all the cases, did you rely on a guide, an article or any reading material? If so, could you leave some links commented below? It might come in handy to know, for someone revisiting this

**Comment by federicobond** [comment]
@slezica the only insight I found was that I could build a `bytearray` out of `bytes` objects to get integers when indexing in Python 2 and 3. You have to be careful because `bytearray` objects are mutable, but as long as they remain behind the public interface, I don't see much problems down the road.

Then there is the trick described [here](http://stackoverflow.com/questions/14043886/python-2-3-convert-integer-to-bytes-cleanly) to get bytes out of integers in both Python versions.

**Comment by federicobond** [comment]
I left the `py.test tests/all.py` command as it was.

**Comment by yemel** [comment]
Awesome!

**Pull request closed without merging**
